Hw04 lru cache
aianushevich/otus_hw pull request #4
Opened 2022-01-05 18:53 UTC by aianushevich

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-01-07 11:30 UTC, agneum requested changes
Спасибо за вариант решения.
Хорошая работа, однако есть критические замечания по работе кэша

Итого: 4 балла из 10
Возвращаю задачу на доработку

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/cache.go
> +	if cache.items[key] == nil {
В Go есть стандартная возможность проверки наличия элемента в мапе по ключу (https://go.dev/blog/maps):
```go
value, ok := cache.items[key]
```
Следует использовать её, т.к. в будущем `nil` может быть валидным значением элемента

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/cache.go
> +		cache.items[key] = cache.queue.Front()
`PushFront` возвращает добавленный элемент. Предлагаю явно использовать его для установки значения без повторного получения первого элемента

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/cache.go
> +		if cache.queue.Len() > cache.capacity {
Желательно проверить заполненность кэша перед добавлением нового элемента, иначе возникнет момент, когда в кэше окажется на один элемент больше указанной capacity

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/cache.go
> +			}
По условию задачи cложность операций Set/Get должна быть O(1), т.е. не должно быть мест, где осуществляется полный перебор элементов.

Рекомендую для исправления этой проблемы использовать удалённую структуру `cacheItem`

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/cache.go
> +	cache.items[key] = cache.queue.Front()
Кажется, избыточное переприсвоение `cache.items[key]`

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/cache.go
> +	}
Аналогично, проверка будет более надёжной
```go
item, ok := cache.items[key]
```

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/cache.go
> +func (cache lruCache) Clear() {
Кэш не очищается

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/cache_test.go
> +		require.False(t, ok)
Не хватает теста с очисткой кэша

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/list.go
> +	slice []*ListItem
Поле структуры выглядит лишним. 
Не до конца понятно, как предполагается его использовать: элементы только добавляются, но никогда не удаляются и не считываются

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/list.go
> +	var newElement ListItem
Предлагаю создать указатель на структуру ListItem и удалить амперсанды по всей функции.
Аналогично для `PushBack()`

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/list.go
> +	if (l.len > 0) && (i != nil) {
В случае отсутствия элементов предлагаю сразу выйти из функции. Это позволит снизить уровень вложенности кода

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/list.go
> +			{
Можно без скобок

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/list.go
> +				l.len--
Похоже, что функция не удаляет первый элемент

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/list.go
> +	}
Можно заменить на комбинацию `Remove()` и `PushFront()`

2022-01-07 11:30 UTC, agneum commented on hw04_lru_cache/list_test.go
> +	})
Предлагаю добавить тест на удаление первого элемента

2022-03-21 04:42 UTC, aianushevich commented on hw04_lru_cache/cache.go
> +			}
Мне не удалось придумать как реализовать это с помощью структуры cacheItem, поэтому я сделал по своему, но правило О(1) учтено

2022-03-21 04:43 UTC, aianushevich commented on hw04_lru_cache/list.go
> +	if (l.len > 0) && (i != nil) {
Если элементов не будет, то содержимое блока if будет проигнорировано. Поэтому немного не понял комментария

2022-03-21 16:13 UTC, agneum approved these changes
Спасибо за правки. Хорошая работа
Итого: 9 баллов из 10

2022-03-21 16:13 UTC, agneum commented on hw04_lru_cache/cache.go
> +	cache.queue = NewList()
`keyMap` не очищается

2022-03-21 16:13 UTC, agneum commented on hw04_lru_cache/list.go
> +	if (l.len > 0) && (i != nil) {
Предлагаю инвертировать условие и сделать внутри `return`, а switch перенести после этого if-блока

2022-03-22 05:42 UTC, merged